version: '3'
services:
   web:
     build: .
     ports:
        - "8083:3000"
        - "8080:8080"
     depends_on:
        - redis
        - mysql
     volumes:
        - "./tmp:/usr/ceshi/tmp"
   redis:
     image: redis
   mysql:
     image: mysql
     environment:
      MYSQL_ROOT_PASSWORD: "666666"

#networks:
#   default:
#    external:
#       name: test-net
